# 0.1 - Initial EDA - MLOps-DBD

Notebook eksplorasi awal (initial EDA), dibuat pada branch `feat/initial-eda`.

Konvensi penamaan notebook: `<nomor>-<inisial>-<deskripsi-singkat>.ipynb`
contoh: `0.1-zr-initial-eda.ipynb`, `0.2-zr-feature-exploration.ipynb`.

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

df = pd.read_csv("../data/raw//latest.csv")
df.head()

,date,page_views,precipitation_sum,temperature_mean,relative_humidity_mean,fetched_at
0,2026-09-22,59,0.0,23.8,67,2026-10-07T16:36:41
1,2026-09-23,34,0.0,23.4,71,2026-10-07T16:36:41
2,2026-09-24,41,0.0,23.9,65,2026-10-07T16:36:41
3,2026-09-25,37,0.0,25.1,61,2026-10-07T16:36:41
4,2026-09-26,20,0.3,25.2,59,2026-10-07T16:36:41

In [5]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    14 non-null     str
 1   page_views              14 non-null     int64
 2   precipitation_sum       14 non-null     float64
 3   temperature_mean        14 non-null     float64
 4   relative_humidity_mean  14 non-null     int64
 5   fetched_at              14 non-null     str
dtypes: float64(2), int64(2), str(2)
memory usage: 804.0 bytes

       page_views  precipitation_sum  temperature_mean  relative_humidity_mean
count   14.000000          14.000000         14.000000               14.000000
mean    38.714286           1.471429         24.192857               71.357143
std     28.440028           2.967109          0.503013                6.476076
min     12.000000           0.000000         23.400000               59.000000
25%     22.250000           0.000000         23.900000               68.000000
50%     32.000000           0.000000         24.200000               72.000000
75%     43.250000           0.925000         24.375000               76.250000
max    126.000000           9.600000         25.200000               81.000000